<!DOCTYPE html>
<html>
<head>
    <title>Report</title>
</head>
<body>
    <h1>Document Repository Report</h1>
    <p>This is a dynamic report generated by our application.</p>export
    <p>${message}</p>
</body>
</html>
